[package]
name = "Office-Booker"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde = { version = "1.0.228", features = ["serde_derive"] }
tokio = {version = "1.48.0", features = ["rt-multi-thread"]}
